### ISSUE TITLE
Chromes 79-81 on Android 9 don't receive SMS

### ISSUE THREAD

**Issue by NOtherDev** [samuelgoto/WebOTP#10]
~~Chrome 79.0.3945.136 on Android 9 doesn't have a permission to read SMS listed and it doesn't ask for it when using SMS Receiver API, thus it's impossible to use this API.~~

Seems the API used on Android doesn't need additional permissions. Nevertheless, even though I have the Origin Trial token in place and the API available, SMS is not received. My test code is [here](https://whatwebcando.today/sms.html).

Tested on Huawei device and on Xiaomi Device, double-checked in the system there's no permission for SMS granted for Chrome app. Also checked Chrome Beta (80.0.3987.68) and Chrome Canary (81.0.4036.0) - same problem.

How would I test this API @samuelgoto?

**Comment by ayuishii** [comment]
A few possible reasons I could think of are:  
 
1. On your website I notice that your formatted SMS message does not include an app hash. Although ideally we would like to remove the requirement of an app hash(https://github.com/samuelgoto/WebOTPs/issues/4), you will need it to receive the SMS for this Origin Trial. 
 
ex) For Chrome App (stable) the SMS will look something like below. More on this [here](https://github.com/samuelgoto/WebOTPs/blob/master/HOWTO.md#app-hashes-for-different-channels).
```
Code: 123ABC
For: https://whatwebcando.today/?otp=123ABC&apphash=EvsSSj4C6vl
```
 
2. SMS Receiver API for Origin Trial is only available from [78-80](https://developers.chrome.com/origintrials/#/view_trial/607985949695016961). It will be turned off for 81. But can still be tested after by turning on [Experimental Web Platform Features](https://github.com/samuelgoto/WebOTP/blob/master/HOWTO.md#trying-it-out) flag.
 
3. Your device needs Play services version 10.2 and newer. This is because it exposes the [SMS Retriever API from GMS Core](https://developers.google.com/identity/sms-retriever/request#prerequisites).

Hope that helps!

**Comment by NOtherDev** [comment]
Yes, thank you @ayuishii. I missed this part about app hash being required and it's not obvious it should be there. It's a pity I need to identify the browser the user is on, though...
